# Generated by Django 4.2.1 on 2023-05-16 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Brand_Name')),
                ('img', models.ImageField(upload_to='Brand_img')),
                ('create_data', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_data', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-create_data', '-update_data'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name product')),
                ('image', models.ImageField(null=True, upload_to='Product_img', verbose_name='image')),
                ('price', models.FloatField(default='0.00', null=True, verbose_name='price')),
                ('quant', models.IntegerField(default='5', null=True, verbose_name='quant')),
                ('description', models.TextField(verbose_name='description')),
                ('color', models.CharField(blank=True, choices=[('blue', 'blue'), ('dark-blue', 'dark-blue'), ('grey', 'grey'), ('golden', 'golden'), ('black', 'black'), ('red', 'red'), ('white', 'white'), ('green', 'green')], max_length=50, null=True, verbose_name='Color')),
                ('create_data', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_data', models.DateTimeField(auto_now=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iphones_app.brand', verbose_name='Brand')),
            ],
            options={
                'ordering': ['-create_data', '-update_data'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, null=True, verbose_name='Product')),
                ('price', models.FloatField(default='0.00', null=True, verbose_name='price')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name='Brand')),
                ('title', models.CharField(max_length=50, verbose_name='Name product')),
                ('quant', models.IntegerField(default='5', null=True, verbose_name='quant')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(null=True, upload_to='Product_img', verbose_name='image')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('create_data', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_data', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_data', '-update_data'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True, verbose_name='description')),
                ('create_data', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_data', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iphones_app.product', verbose_name='product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_data', '-update_data'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default='0.00', null=True, verbose_name='price')),
                ('title', models.CharField(max_length=50, verbose_name='Name product')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(null=True, upload_to='Product_img', verbose_name='image')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('create_data', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_data', models.DateTimeField(auto_now=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iphones_app.brand', verbose_name='Brand')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iphones_app.product', verbose_name='Brand')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_data', '-update_data'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default='0.00', null=True, verbose_name='price')),
                ('quant', models.IntegerField(default='5', null=True, verbose_name='quant')),
                ('title', models.CharField(max_length=50, verbose_name='Name product')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(null=True, upload_to='Product_img', verbose_name='image')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('create_data', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_data', models.DateTimeField(auto_now=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iphones_app.brand', verbose_name='Brand')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iphones_app.product', verbose_name='Brand')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_data', '-update_data'],
            },
        ),
    ]
