# Generated by Django 4.2.1 on 2023-05-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iphones_app', '0002_alter_opinion_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='color',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='description',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='image',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iphones_app.product', verbose_name='Brand'),
        ),
    ]
