# Generated by Django 4.2.1 on 2023-05-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphones_app', '0004_alter_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Contacter_Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Contacter_Email')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Contacter_Phone_Number')),
                ('message', models.TextField(null=True, verbose_name='Contacter')),
                ('create_data', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_data', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-create_data', '-update_data'],
            },
        ),
    ]
